# Generated by Django 2.1.1 on 2018-10-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_auto_20181003_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingcompany',
            name='api_type',
            field=models.CharField(blank=True, choices=[('emspost', 'EMS VietNam Post REST API')], max_length=10, verbose_name='API type'),
        ),
        migrations.AlterField(
            model_name='shippingcompany',
            name='origin',
            field=models.CharField(blank=True, default='Hà Nội', max_length=255, verbose_name='City of origin'),
        ),
    ]
